use std::fs;
use std::process::Command;

use maledictus::protocol::{
    ExternalExceptionPolicy, ExternalOverlay, PROTOCOL_SCHEMA, ProofRequest, ProofStatus,
    SourceFile,
};
use maledictus::python_typecheck::{MYPY_VERSION, typecheck_request_sources};
use maledictus::{FrontendDisposition, analyze_python_frontend};

fn python_file(path: &str) -> SourceFile {
    SourceFile {
        path: path.to_owned(),
        language: "python".to_owned(),
        symbols: Vec::new(),
    }
}

#[test]
fn exact_real_mypy_strictly_checks_bound_source_and_records_identity() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "def identity(value: int) -> int:\n    return value\n",
    )
    .unwrap();

    let verification = typecheck_request_sources(directory.path(), &[python_file("app.py")], &[])
        .expect("the pinned checker must be available for the issuance test")
        .expect("the request contains Python");
    assert!(verification.passed(), "{verification:#?}");
    assert_eq!(verification.identity.checker, "mypy");
    assert_eq!(verification.identity.checker_version, MYPY_VERSION);
    assert_eq!(verification.identity.profile, "strict-issuance");
    assert_eq!(verification.identity.package_sha256.len(), 64);
    assert_eq!(verification.identity.runtime_executable_sha256.len(), 64);
    assert_eq!(verification.identity.runtime_bundle_sha256.len(), 64);
    assert_eq!(verification.identity.configuration_sha256.len(), 64);
    assert_eq!(
        verification
            .identity
            .contract_support_sha256
            .as_deref()
            .map(str::len),
        Some(64)
    );

    let repeated = typecheck_request_sources(directory.path(), &[python_file("app.py")], &[])
        .expect("the pinned checker must remain available")
        .expect("the request contains Python");
    assert_eq!(
        repeated.identity, verification.identity,
        "toolchain identity must not depend on generated bytecode caches or temporary paths"
    );
}

#[test]
fn concurrent_typechecks_keep_mypy_cache_out_of_the_shared_source_root() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "def identity(value: int) -> int:\n    return value\n",
    )
    .unwrap();

    let (first, second) = std::thread::scope(|scope| {
        let first = scope
            .spawn(|| typecheck_request_sources(directory.path(), &[python_file("app.py")], &[]));
        let second = scope
            .spawn(|| typecheck_request_sources(directory.path(), &[python_file("app.py")], &[]));
        (first.join().unwrap(), second.join().unwrap())
    });
    let first = first.unwrap().unwrap();
    let second = second.unwrap().unwrap();
    assert!(first.passed(), "{first:#?}");
    assert!(second.passed(), "{second:#?}");
    assert_eq!(first.identity, second.identity);
    assert!(
        !directory.path().join(".mypy_cache").exists(),
        "mypy cache escaped its invocation-owned overlay workspace"
    );
}

#[test]
fn strict_type_errors_are_located_and_block_proof_issuance() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "def wrong(value: int) -> str:\n    return value\n",
    )
    .unwrap();
    let request = ProofRequest {
        schema: PROTOCOL_SCHEMA.to_owned(),
        source_root: directory.path().display().to_string(),
        source_fingerprint: "0".repeat(64),
        proof_obligation: "no-undeclared-exceptional-exit".to_owned(),
        files: vec![SourceFile {
            path: "app.py".to_owned(),
            language: "python".to_owned(),
            symbols: vec!["wrong".to_owned()],
        }],
        external_contract_overlays: Vec::new(),
        python_callable_bindings: Vec::new(),
        cross_language_bindings: Vec::new(),
    };

    let response = maledictus::verify(&request);
    assert!(
        matches!(response.status, ProofStatus::Refused),
        "{response:#?}"
    );
    assert!(response.python_typechecker.is_some(), "{response:#?}");
    assert_eq!(response.diagnostics.len(), 1, "{response:#?}");
    assert_eq!(
        response.diagnostics[0].code,
        "frontend.python.typecheck.return-value"
    );
    assert_eq!(response.diagnostics[0].path.as_deref(), Some("app.py"));
    assert_eq!(response.diagnostics[0].line, Some(2));
    assert_eq!(response.diagnostics[0].column, Some(12));
    assert!(response.files.is_empty(), "proof lowering must not begin");
}

#[test]
fn strict_profile_does_not_silently_accept_untyped_application_functions() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "def untyped(value):\n    return value\n",
    )
    .unwrap();

    let verification = typecheck_request_sources(directory.path(), &[python_file("app.py")], &[])
        .unwrap()
        .unwrap();
    assert!(!verification.passed(), "{verification:#?}");
    assert!(
        verification
            .diagnostics
            .iter()
            .any(|diagnostic| { diagnostic.code == "frontend.python.typecheck.no-untyped-def" })
    );
}

#[test]
fn unrequested_local_imports_cannot_influence_a_clean_typecheck() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("provider.py"),
        "def value() -> int:\n    return 1\n",
    )
    .unwrap();
    fs::write(
        directory.path().join("app.py"),
        "from provider import value\n\ndef read() -> int:\n    return value()\n",
    )
    .unwrap();

    let refused = typecheck_request_sources(directory.path(), &[python_file("app.py")], &[])
        .unwrap()
        .unwrap();
    assert!(!refused.passed(), "{refused:#?}");
    assert!(refused.diagnostics.iter().any(|diagnostic| {
        diagnostic.code == "frontend.python.typecheck.misc" && diagnostic.line == Some(1)
    }));

    let closed = typecheck_request_sources(
        directory.path(),
        &[python_file("app.py"), python_file("provider.py")],
        &[],
    )
    .unwrap()
    .unwrap();
    assert!(closed.passed(), "{closed:#?}");
}

#[test]
fn declared_external_overlay_is_a_typed_explicit_input_not_an_ignored_import() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "from provider import positive\nfrom nagini_contracts.contracts import *\n\ndef run() -> int:\n    Ensures(Result() == 2)\n    value = positive(1)\n    return value\n",
    )
    .unwrap();
    fs::write(
        directory.path().join("provider_contract.py"),
        "from nagini_contracts.contracts import *\n\n@ContractOnly\ndef positive(value: int) -> int:\n    Requires(value > 0)\n    Ensures(int, lambda returned: returned == value + 1)\n    ...\n",
    )
    .unwrap();
    let overlay = ExternalOverlay {
        adapter_path: "app.py".to_owned(),
        module: "provider".to_owned(),
        stub_path: "provider_contract.py".to_owned(),
        exception_policy: ExternalExceptionPolicy::AssumeNoException,
    };

    let verification =
        typecheck_request_sources(directory.path(), &[python_file("app.py")], &[overlay])
            .unwrap()
            .unwrap();
    assert!(verification.passed(), "{verification:#?}");
}

#[test]
fn generated_external_interface_is_strictly_checked_without_blanket_suppression() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "from provider import convert\n\ndef run(value: int) -> int:\n    return convert(value)\n",
    )
    .unwrap();
    fs::write(
        directory.path().join("provider_contract.py"),
        "def convert(value):\n    ...\n",
    )
    .unwrap();
    let overlay = ExternalOverlay {
        adapter_path: "app.py".to_owned(),
        module: "provider".to_owned(),
        stub_path: "provider_contract.py".to_owned(),
        exception_policy: ExternalExceptionPolicy::AssumeNoException,
    };

    let verification =
        typecheck_request_sources(directory.path(), &[python_file("app.py")], &[overlay])
            .unwrap()
            .unwrap();
    assert!(!verification.passed(), "{verification:#?}");
    assert!(verification.diagnostics.iter().any(|diagnostic| {
        diagnostic.path.as_deref() == Some("provider_contract.py")
            && diagnostic.code == "frontend.python.typecheck.no-untyped-def"
    }));
}

#[test]
fn nagini_contract_primitives_keep_typed_signatures_under_the_strict_profile() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "from nagini_contracts.contracts import Ensures, Result\n\ndef identity(value: int) -> int:\n    Ensures(Result() == value)\n    return value\n",
    )
    .unwrap();

    let verification = typecheck_request_sources(directory.path(), &[python_file("app.py")], &[])
        .unwrap()
        .unwrap();
    assert!(verification.passed(), "{verification:#?}");
}

#[test]
fn strict_profile_targets_nagini_python_312_semantics_independent_of_runtime() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "from typing import override\n\nclass Base:\n    def value(self) -> int:\n        return 1\n\nclass Derived(Base):\n    @override\n    def value(self) -> int:\n        return 2\n",
    )
    .unwrap();

    let verification = typecheck_request_sources(directory.path(), &[python_file("app.py")], &[])
        .unwrap()
        .unwrap();
    assert!(verification.passed(), "{verification:#?}");
}

#[test]
fn source_paths_are_confined_before_starting_the_external_checker() {
    let directory = tempfile::tempdir().unwrap();
    let error = typecheck_request_sources(directory.path(), &[python_file("../outside.py")], &[])
        .unwrap_err();
    assert_eq!(error.code, "frontend.python.typecheck.source-path");
}

#[test]
fn non_issuing_analysis_is_explicit_and_cannot_bypass_verify() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "def wrong(value: int) -> str:\n    return value\n",
    )
    .unwrap();
    let request = ProofRequest {
        schema: PROTOCOL_SCHEMA.to_owned(),
        source_root: directory.path().display().to_string(),
        source_fingerprint: "0".repeat(64),
        proof_obligation: "no-undeclared-exceptional-exit".to_owned(),
        files: vec![SourceFile {
            path: "app.py".to_owned(),
            language: "python".to_owned(),
            symbols: vec!["wrong".to_owned()],
        }],
        external_contract_overlays: Vec::new(),
        python_callable_bindings: Vec::new(),
        cross_language_bindings: Vec::new(),
    };

    let issuance = maledictus::verify(&request);
    assert!(matches!(issuance.status, ProofStatus::Refused));
    assert!(issuance.python_typechecker.is_some());
    assert!(issuance.files.is_empty(), "proof lowering must not begin");

    let analysis = analyze_python_frontend(&request);
    assert!(
        matches!(
            analysis.disposition,
            FrontendDisposition::Supported
                | FrontendDisposition::Refuted
                | FrontendDisposition::Unsupported
        ),
        "{analysis:#?}"
    );
    assert!(!analysis.files.is_empty(), "{analysis:#?}");
    assert!(
        analysis
            .diagnostics
            .iter()
            .all(|item| !item.code.starts_with("frontend.python.typecheck.")),
        "{analysis:#?}"
    );
}

#[test]
fn protocol_and_verify_cli_reject_an_analysis_mode_switch() {
    let directory = tempfile::tempdir().unwrap();
    fs::write(
        directory.path().join("app.py"),
        "def identity(value: int) -> int:\n    return value\n",
    )
    .unwrap();
    let request = ProofRequest {
        schema: PROTOCOL_SCHEMA.to_owned(),
        source_root: directory.path().display().to_string(),
        source_fingerprint: "0".repeat(64),
        proof_obligation: "no-undeclared-exceptional-exit".to_owned(),
        files: vec![python_file("app.py")],
        external_contract_overlays: Vec::new(),
        python_callable_bindings: Vec::new(),
        cross_language_bindings: Vec::new(),
    };
    let mut encoded = serde_json::to_value(&request).unwrap();
    encoded["analysis"] = serde_json::Value::Bool(true);
    assert!(serde_json::from_value::<ProofRequest>(encoded.clone()).is_err());

    let request_path = directory.path().join("request.json");
    fs::write(&request_path, serde_json::to_vec_pretty(&encoded).unwrap()).unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_maledictus"))
        .args(["verify", "--request"])
        .arg(request_path)
        .output()
        .unwrap();
    assert!(!output.status.success());
    assert!(output.stdout.is_empty());
}
